### ISSUE TITLE
Add metafacture as ETL-Tool for MARC

### ISSUE THREAD

**Issue by TobiasNx** [jorol/processing-marc#1]
You could add Metafacture as open-source ETL-Tool, which is able to process MARC 21 and MARC-xml (as well as other library formats e.g. PICA).
https://github.com/metafacture/metafacture-core

**Comment by jorol** [comment]
Thanks for the hint. Metafacture is already referenced in the list of "[Catmandu - Related projects](https://librecat.org/Catmandu/#selected-formats)" under "[More tools](https://jorol.github.io/processing-marc/#/tools?id=more-tools)". I really don't want to maintain a list of all these tools on this site, just for the tools used in the tutorial.
